export const AppFonts = {
  breeSerif: 'BreeSerif',
  interBlack: 'Inter-Black',
  interBlackItalic: 'Inter-BlackItalic',
  interBold: 'Inter-Bold',
  interBoldItalic: 'Inter-BoldItalic',
  interExtraBold: 'Inter-ExtraBold',
  interExtraBoldItalic: 'Inter-ExtraBoldItalic',
  interExtraLight: 'Inter-ExtraLight',
  interExtraLightItalic: 'Inter-ExtraLightItalic',
  interItalic: 'Inter-Italic',
  interLight: 'Inter-Light',
  interLightItalic: 'Inter-LightItalic',
  interMedium: 'Inter-Medium',
  interMediumItalic: 'Inter-MediumItalic',
  interRegular: 'Inter-Regular',
  interSemiBold: 'Inter-SemiBold',
  interSemiBoldItalic: 'Inter-SemiBoldItalic',
  interThin: 'Inter-Thin',
  interThinItalic: 'Inter-ThinItalic',
} as const;

export const AppFontSources = {
  [AppFonts.breeSerif]: require('./BreeSerif-Regular.ttf'),
  [AppFonts.interBlack]: require('./Inter-Black.otf'),
  [AppFonts.interBlackItalic]: require('./Inter-BlackItalic.otf'),
  [AppFonts.interBold]: require('./Inter-Bold.otf'),
  [AppFonts.interBoldItalic]: require('./Inter-BoldItalic.otf'),
  [AppFonts.interExtraBold]: require('./Inter-ExtraBold.otf'),
  [AppFonts.interExtraBoldItalic]: require('./Inter-ExtraBoldItalic.otf'),
  [AppFonts.interExtraLight]: require('./Inter-ExtraLight-BETA.otf'),
  [AppFonts.interExtraLightItalic]: require('./Inter-ExtraLightItalic-BETA.otf'),
  [AppFonts.interItalic]: require('./Inter-Italic.otf'),
  [AppFonts.interLight]: require('./Inter-Light-BETA.otf'),
  [AppFonts.interLightItalic]: require('./Inter-LightItalic-BETA.otf'),
  [AppFonts.interMedium]: require('./Inter-Medium.otf'),
  [AppFonts.interMediumItalic]: require('./Inter-MediumItalic.otf'),
  [AppFonts.interRegular]: require('./Inter-Regular.otf'),
  [AppFonts.interSemiBold]: require('./Inter-SemiBold.otf'),
  [AppFonts.interSemiBoldItalic]: require('./Inter-SemiBoldItalic.otf'),
  [AppFonts.interThin]: require('./Inter-Thin-BETA.otf'),
  [AppFonts.interThinItalic]: require('./Inter-ThinItalic-BETA.otf'),
} as const;
