/** Font family names to use in styles: `fontFamily: fonts.interBold`. */
export const fonts = {
  breeSerif: 'BreeSerif',
  interBlack: 'Inter-Black',
  interBlackItalic: 'Inter-BlackItalic',
  interBold: 'Inter-Bold',
  interBoldItalic: 'Inter-BoldItalic',
  interExtraBold: 'Inter-ExtraBold',
  interExtraBoldItalic: 'Inter-ExtraBoldItalic',
  interExtraLight: 'Inter-ExtraLight',
  interExtraLightItalic: 'Inter-ExtraLightItalic',
  interItalic: 'Inter-Italic',
  interLight: 'Inter-Light',
  interLightItalic: 'Inter-LightItalic',
  interMedium: 'Inter-Medium',
  interMediumItalic: 'Inter-MediumItalic',
  interRegular: 'Inter-Regular',
  interSemiBold: 'Inter-SemiBold',
  interSemiBoldItalic: 'Inter-SemiBoldItalic',
  interThin: 'Inter-Thin',
  interThinItalic: 'Inter-ThinItalic',
  archivoBold: 'Archivo-Bold',
  archivoMedium: 'Archivo-Medium',
  archivoRegular: 'Archivo-Regular',
  archivoSemiBold: 'Archivo-SemiBold',
  SFProDisplayBold: 'SF-Pro-Display-Bold',
  SFProDisplayLight: 'SF-Pro-Display-Light',
  SFProDisplayMedium: 'SF-Pro-Display-Medium',
  SFProDisplayRegular: 'SF-Pro-Display-Regular',
  SFProDisplaySemiBold: 'SF-Pro-Display-Semibold',
} as const;