/** Font family names to use in styles: `fontFamily: fonts.interBold`. */
export const fonts = {
  breeSerif: 'BreeSerif',
  interBlack: 'Inter-Black',
  interBlackItalic: 'Inter-BlackItalic',
  interBold: 'Inter-Bold',
  interBoldItalic: 'Inter-BoldItalic',
  interExtraBold: 'Inter-ExtraBold',
  interExtraBoldItalic: 'Inter-ExtraBoldItalic',
  interExtraLight: 'Inter-ExtraLight',
  interExtraLightItalic: 'Inter-ExtraLightItalic',
  interItalic: 'Inter-Italic',
  interLight: 'Inter-Light',
  interLightItalic: 'Inter-LightItalic',
  interMedium: 'Inter-Medium',
  interMediumItalic: 'Inter-MediumItalic',
  interRegular: 'Inter-Regular',
  interSemiBold: 'Inter-SemiBold',
  interSemiBoldItalic: 'Inter-SemiBoldItalic',
  interThin: 'Inter-Thin',
  interThinItalic: 'Inter-ThinItalic',
} as const;

/** Passed to `useFonts()` in App.tsx. */
export const fontSources = {
  [fonts.breeSerif]: require('./BreeSerif-Regular.ttf'),
  [fonts.interBlack]: require('./Inter-Black.otf'),
  [fonts.interBlackItalic]: require('./Inter-BlackItalic.otf'),
  [fonts.interBold]: require('./Inter-Bold.otf'),
  [fonts.interBoldItalic]: require('./Inter-BoldItalic.otf'),
  [fonts.interExtraBold]: require('./Inter-ExtraBold.otf'),
  [fonts.interExtraBoldItalic]: require('./Inter-ExtraBoldItalic.otf'),
  [fonts.interExtraLight]: require('./Inter-ExtraLight-BETA.otf'),
  [fonts.interExtraLightItalic]: require('./Inter-ExtraLightItalic-BETA.otf'),
  [fonts.interItalic]: require('./Inter-Italic.otf'),
  [fonts.interLight]: require('./Inter-Light-BETA.otf'),
  [fonts.interLightItalic]: require('./Inter-LightItalic-BETA.otf'),
  [fonts.interMedium]: require('./Inter-Medium.otf'),
  [fonts.interMediumItalic]: require('./Inter-MediumItalic.otf'),
  [fonts.interRegular]: require('./Inter-Regular.otf'),
  [fonts.interSemiBold]: require('./Inter-SemiBold.otf'),
  [fonts.interSemiBoldItalic]: require('./Inter-SemiBoldItalic.otf'),
  [fonts.interThin]: require('./Inter-Thin-BETA.otf'),
  [fonts.interThinItalic]: require('./Inter-ThinItalic-BETA.otf'),
} as const;
