/**
 * PNG icon assets. Use with `<Image source={icons.logo} />`.
 * Every file is a black glyph on a transparent background, so tint it via
 * `style={{ tintColor }}` to match the surface it sits on.
 */
export const icons = {
  diagram: require('./diagram.png'),
  logo: require('./logo.png'),
  pieChart: require('./pie-chart.png'),
  chart: require('./chart.png'),
  security: require('./security.png'),
  target: require('./target.png'),
  sparkle: require('./sparkle.png'),
  burger: require('./burger.png'),
  car: require('./car.png'),
  paper: require('./paper.png'),
  plus: require('./plus.png'),
  rightArrow: require('./right-arrow.png'),
  signalStatus: require('./signal-status.png'),
  smart: require('./smart.png'),
  border1: require('./border1.png'),
  border2: require('./border2.png'),
  lineTrack: require('./lineTrack.png'),
  starCircle: require('./starCircle.png'),
  checkSuccess: require('./checkSuccess.png'),
  timer: require('./timer.png'),
  sendTrack: require('./sendTrack.png'),
  targetPin: require('./targetPin.png'),
  card: require('./card.png'),
  network: require('./network.png'),
  sparkleGreen: require('./sparkleGreen.png'),
  doc: require('./doc.png'),
  add: require('./add.png'),
  arrow_right: require('./arrow_right.png'),
  notification: require('./notification.png'),
  networkGradient: require('./networkGradient.png'),
  wallet: require('./wallet.png'),
  cartGradient: require('./cartGradient.png'),
  saftey: require('./saftey.png'),
  leaf: require('./leaf.png'),
  ruppes: require('./ruppes.png'),
  pin: require('./pin.png'),
  arrow_sparkle: require('./arrow_sparkle.png'),
  power: require('./power.png'),
  privacyCheck: require('./privacyCheck.png'),
  targetCopy: require('./targetCopy.png'),
  track: require('./track.png'),
  goals: require('./goals.png'),
  trophy: require('./trophy.png'),
  shape1: require('./shape1.png'),
  shape2: require('./shape2.png'),
  circleChart: require('./circleChart.png'),
  lock: require('./lock.png'),
  documents: require('./documents.png'),
  polygon: require('./polygon.png'),
} as const;

export type IconName = keyof typeof icons;
